openapi: 3.0.1
info:
  description: |
    The Credit Pros - DEV Portal 2.0 API
  version: '1.1'
  title: Portal 2.0 API
  termsOfService: 'http://www.thecreditpros.com/terms/'
  contact:
    email: apiteam@thecreditpros.com
servers:
  # Added by API Auto Mocking Plugin
  - description: AWS GW Dev Environment
    url: https://api-dev2.thecreditpros.com/portal2
  
tags:
  - name: Activity
    description: Endpoints within this category pertain to client activities, encompassing both routine actions and those associated with exports.

    
paths:
  # ACTIVITY ENDPOINTS
  /api/item_activity/{clientid}/{itemid}:
    get:
      tags:
        - Activity
      summary: Get all Item Activities
      description: >-
        Retrieve item activities by providing a Bearer token in the
        'Authorization' header.
      operationId: getItemActivity
      security:
        - api_key: []
      parameters:
        - name: "x-api-key"
          in: "header"
          required: true
          schema:
            type: "string"
        - name: "Authorization"
          in: "header"
          required: true
          schema:
            type: "string"
        - name: clientid
          in: path
          description: Client ID for which the activities are to be retrieved (e.g., 1600)
          required: true
          schema:
            type: integer
        - name: itemid
          in: path
          description: Item ID (e.g., 1)
          required: true
          schema:
            type: integer
        - name: search
          in: query
          description: Search text
          required: false
          schema:
            type: string
        - name: sort_column
          in: query
          description: Column name based on which the results are to be sorted
          required: false
          schema:
            type: string
        - name: sort_direction
          in: query
          description: Sort direction (asc or desc)
          required: false
          schema:
            type: string
            enum:
              - desc
              - asc
        - name: perpage
          in: query
          description: Number of results required per page
          required: false
          schema:
            type: integer
      responses:
        200:
          description: Activity listing successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/200GetItemActivity'
        401:
          description: Unauthorized
      x-amazon-apigateway-integration:
        httpMethod: "GET"
        uri: "https://portal2.dev.thecreditpros.com/api/item_activity/{clientid}/{itemid}"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.header.x-api-key: "method.request.header.x-api-key"
          integration.request.header.Authorization: "method.request.header.Authorization"
          integration.request.path.clientid: "method.request.querystring.clientid"
          integration.request.path.itemid: "method.request.querystring.itemid"
          integration.request.querystring.search: "method.request.querystring.search"
          integration.request.querystring.sort_column: "method.request.querystring.sort_column"
          integration.request.querystring.sort_direction: "method.request.querystring.sort_direction"
          integration.request.querystring.perpage: "method.request.querystring.perpage"
        passthroughBehavior: "when_no_match"
        type: "http"
  

components:
  securitySchemes:
    #bearerAuth:           
      #type: http
      #scheme: bearer
      #bearerFormat: JWT
    api_key:
      type: "apiKey"
      name: "x-api-key"
      in: "header"
      
  schemas:
    200GetItemActivity:
      properties:
        status: 
          type: string
          example: success
        message: 
          type: string
          example: Activity listing successfully
        code: 
          type: number
          example: 200
        results: 
          type: object
          properties: 
            current_page: 
              type: number
              example: 1
            data: 
              type: array
              items: 
                type: object
                properties: 
                  id: 
                    type: number
                    example: 153604390
                  ip_address_stamp: 
                    type: string
                    example: 172.70.246.246
                  activity: 
                    type: string
                    format: nullable
                  text_override: 
                    type: string
                    example: A new letter added to client [ACTIVITY_FOR] for experian item PREMIER MEMBERS CU via sequence step.
                  is_client: 
                    type: number
                    example: 1
                  by_user_id: 
                    type: number
                    example: 0
                  date_created: 
                    type: string
                    example: 2022-10-20 08:41:06
                  type: 
                    type: string
                    example: new
                  by_user_type: 
                    type: string
                    example: Client
                  by_user: 
                    type: string
                    example: Thomassg Friedman
                  month: 
                    type: string
                    example: October
                  year: 
                    type: string
                    example: 2022
                  link: 
                    type: string
                    example: Client
                  about_id: 
                    type: number
                    example: 49192
                  activity_for: 
                    type: string
                    example: Thomassg Friedman
            first_page_url: 
              type: string
              example: http://portal2.dev.thecreditpros.com/api/item_activity/49192/5383198?page=1
            from: 
              type: number
              example: 1
            last_page: 
              type: number
              example: 1
            last_page_url: 
              type: string
              example: http://portal2.dev.thecreditpros.com/api/item_activity/49192/5383198?page=1
            links: 
              type: array
              items: 
                type: object
                properties: 
                  url: 
                    type: string
                    format: nullable
                  label: 
                    type: string
                    example: Previous
                  active: 
                    type: boolean
            next_page_url: 
              type: string
              format: nullable
            path: 
              type: string
              example: http://portal2.dev.thecreditpros.com/api/item_activity/49192/5383198
            per_page: 
              type: number
              example: 10
            prev_page_url: 
              type: string
              format: nullable
            to: 
              type: number
              example: 7
            total: 
              type: number
              example: 7
    

x-aws-api-id: 'u7xdb3zrb1'